# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.3.1
group=com.onlytp.onlytpmod
java_version=17

# Common
minecraft_version=1.19.2
mod_name=Only TP
mod_author=Huziyang520
mod_id=onlytp
license=MIT
credits=
description=Restrict players to using only TP-related commands, or completely disable non-TP commands. \nIssues: https://github.com/Huziyang520/Only-TP/issues | https://issue.mengcai.online/
minecraft_version_range=[1.19.2, 1.20)
# Parchment is intentionally omitted for 1.19.2 to avoid nonexistent version download failures.

# Fabric
fabric_version=0.76.0+1.19.2
fabric_loader_version=0.14.24

# Forge
forge_version=43.4.0
forge_loader_version_range=[43,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
