org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

## Minecraft & NeoForge 版本
minecraft_version=1.21.1
neo_version=21.1.226
minecraft_version_range=[1.21.1,1.22)
loader_version_range=[4,)

## 模组属性
mod_id=onlytp
mod_name=Only TP
mod_license=MIT
mod_version=1.0.5.2
mod_group_id=com.onlytp.onlytpmod
mod_authors=Only TP Contributors
mod_description=限制玩家只能使用TP类指令，或完全禁用非TP指令。
